### ISSUE TITLE
FASTA database rather than Centrifuge

### ISSUE THREAD

**Issue by PWSmit** [JordyCoolen/MyCodentifier#1]
Hi Jordy! 

Cool paper! 
Could you perhaps share the Centrifuge reference dataset as FASTA (or give a way to extract it from Centrifuge)? 
thanks 
Pieter

**Comment by JordyCoolen** [comment]
Hi Pieter!

Thank you:)
Yes you can convert the centrifuge index back to every input format used to create it. Also the FASTA file.

This is for extracting to fasta:
centrifuge-inspect <centrifuge index>

More documentation can be found here:
http://www.ccb.jhu.edu/software/centrifuge/manual.shtml
At the section, Inspecting the Centrifuge Index.

Kind regards,
Jordy
